# TODO: Config the theme further.
theme = "aumnechroma-theme"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true
bufferline = "multiple"
scrolloff = 12
mouse = true
middle-click-paste = false
gutters = [
  "diagnostics",
  "spacer",
  "line-numbers",
  "spacer",
  "diff",            # I might not want to see this.
]
auto-completion = true  
auto-format = true    # Not sure if I want this.
idle-timeout = 200
completion-trigger-len = 2
completion-replace = false
auto-info = true
text-width = 94
auto-pairs = true

[editor.soft-wrap]
enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control"]
center = []
right = ["diagnostics", "selections", "position", "position-percentage", "total-line-numbers", "file-encoding", "file-type"]
separator = "|"
mode.normal = "NORMAl"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = false
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true

# TODO: Config all the rest of the keys.
[keys.normal]
l = "command_mode"
C-p = "command_palette"

u = "undo"
C-r = "redo"

h = "move_visual_line_down"
t = "move_visual_line_up"
H = "half_page_down"
T = "half_page_up"

q = "move_char_left"
e = "move_char_right"

n = "move_next_word_start"
o = "move_prev_word_start"

g = { g = "goto_file_start", o = "goto_line_start", n = "goto_line_end", c = { a = "code_action" }, d = "goto_definition", h = "hover" }

w = "insert_mode"
W = "insert_at_line_start"
a = "append_mode"
A = "insert_at_line_end"

s = "delete_selection_noyank"
k = "change_selection_noyank"

# TODO, these don't work yet, really.
p = "paste_before"
P = "paste_after"

r = "search"
b = "search_next"
B = "search_prev"

tab = "indent"
S-tab = "unindent"

v = "select_mode"
"esc" = "exit_select_mode"

C-S-p = "file_picker_in_current_directory"

# End of File
