# Aumnechroma for Helix | Syntax highlighting
# -------------------
"type"                          = "fg_yellow_12_rite_of_spring"

"constructor"                   = "fg_cyan_01_verdigris"

"constant"                      = "fg_white_01_seashell"
"constant.builtin"              = "fg_white_01_seashell"
"constant.character"            = "fg_cyan_03_shimmering_expanse"
"constant.character.escape"     = "fg_red_04_anime_blush"

"string"                        = "fg_green_07_iguana_green"
"string.regexp"                 = "fg_white_01_seashell"
"string.special"                = "fg_blue_12_fennel_flower"

"comment"                       = { fg = "special_01_dahlia_purple",    modifiers = ["italic"] }

"variable"                      = "fg_white_00_icy_landscape"
"variable.parameter"            = { fg = "fg_red_02_festive_fennec",      modifiers = ["italic"] }
"variable.builtin"              = "fg_red_01_infrared"
"variable.other.member"         = "fg_white_04_"

"label"                         = "fg_cyan_01_verdigris" # Used for lifetimes

"punctuation"                   = "fg_cyan_04_thousand_sons"
"punctuation.special"           = "fg_cyan_02_windswept"

"keyword"                       = "fg_purple_22_lical_geode"
"keyword.control.conditional"   = { fg = "fg_purple_22_lical_geode",       modifiers = ["italic"] }

"operator"                      = "fg_red_01_infrared"

"function"                      = "fg_blue_12_fennel_flower"
"function.macro"                = "fg_purple_22_lical_geode"

"tag"                           = "fg_purple_22_lical_geode"
"attribute"                     = "fg_blue_12_fennel_flower"

"namespace"                     = { fg = "fg_blue_12_fennel_flower",        modifiers = ["italic"] }

"special"                       = "fg_blue_12_fennel_flower" # fuzzy highlight

"markup.heading.marker"         = { fg = "fg_white_01_seashell",       modifiers = ["bold"] }
"markup.heading.1"              = "fg_blue_01_blue_genie"
"markup.heading.2"              = "fg_purple_22_lical_geode"
"markup.heading.3"              = "fg_green_07_iguana_green"
"markup.heading.4"              = "fg_yellow_12_rite_of_spring"
"markup.heading.5"              = "fg_red_04_anime_blush"
"markup.heading.6"              = "fg_cyan_03_shimmering_expanse"
"markup.list"                   = "fg_purple_22_lical_geode"
"markup.bold"                   = { modifiers = ["bold"] }
"markup.italic"                 = { modifiers = ["italic"] }
"markup.link.url"               = { fg = "fg_white_11_icy_plains",   modifiers = ["italic", "underlined"] }
"markup.link.text"              = "fg_blue_12_fennel_flower"
"markup.raw"                    = "flamingo"

"diff.plus"                     = "fg_green_07_iguana_green"
"diff.minus"                    = "fg_red_01_infrared"
"diff.delta"                    = "fg_blue_12_fennel_flower"

# User Interface
# --------------
"ui.background"                 = { fg = "fg_white_00_icy_landscape", bg = "bg_02_remnant" }

"ui.linenr"                     = { fg = "bg_06_dusk" }
"ui.linenr.selected"            = { fg = "fg_blue_01_blue_genie" }

"ui.statusline"                 = { fg = "fg_white_07_hint_of_blue",    bg = "bg_03_night" }
"ui.statusline.inactive"        = { fg = "surface2",                    bg = "bg_03_night" }
"ui.statusline.normal"          = { fg = "bg_02_remnant",                        bg = "fg_blue_01_blue_genie",       modifiers = ["bold"] }
"ui.statusline.insert"          = { fg = "bg_02_remnant",                        bg = "fg_green_07_iguana_green",    modifiers = ["bold"]  }
"ui.statusline.select"          = { fg = "bg_02_remnant",                        bg = "flamingo",                    modifiers = ["bold"]  }

"ui.popup"                      = { fg = "fg_white_00_icy_landscape", bg = "bg_05_tristesse" }
"ui.window"                     = { fg = "bg_01_darkcrust" }
"ui.help"                       = { fg = "bg_08_ghost", bg = "bg_05_tristesse" }

"ui.bufferline"                 = { fg = "fg_white_07_hint_of_blue", bg = "bg_03_night" }
"ui.bufferline.active"          = { fg = "fg_purple_22_lical_geode", bg = "bg_02_remnant", underline = { color = "fg_purple_22_lical_geode", style = "line" } }
"ui.bufferline.background"      = { bg = "bg_01_darkcrust" }

"ui.text"                       = "fg_white_00_icy_landscape"
"ui.text.focus"                 = { fg = "fg_white_00_icy_landscape",        bg = "bg_05_tristesse",    modifiers = ["bold"] }

"ui.virtual"                    = "overlay0"
"ui.virtual.ruler"              = { bg = "bg_05_tristesse" }
"ui.virtual.indent-guide"       = "bg_05_tristesse"
"ui.virtual.inlay-hint"         = { fg = "bg_06_dusk",    bg = "bg_03_night" }

"ui.selection"                  = { bg = "bg_06_dusk" }

"ui.cursor"                     = { fg = "bg_02_remnant",           bg = "secondary_cursor" }
"ui.cursor.primary"             = { fg = "bg_02_remnant",           bg = "fg_white_11_icy_plains" }
"ui.cursor.match"               = { fg = "fg_white_01_seashell",    modifiers = ["bold"] }

"ui.cursorline.primary"         = { bg = "cursorline" }

"ui.highlight"                  = { bg = "bg_06_dusk",    modifiers = ["bold"] }

"ui.menu"                       = { fg = "bg_08_ghost",    bg = "bg_05_tristesse" }
"ui.menu.selected"              = { fg = "fg_white_00_icy_landscape",        bg = "bg_06_dusk",    modifiers = ["bold"] }

"diagnostic.error"              = { underline = { color = "fg_red_01_infrared",                 style = "curl" } }
"diagnostic.warning"            = { underline = { color = "fg_yellow_12_rite_of_spring",        style = "curl" } }
"diagnostic.info"               = { underline = { color = "fg_blue_08_widowmaker",              style = "curl" } }
"diagnostic.hint"               = { underline = { color = "fg_cyan_03_shimmering_expanse",      style = "curl" } }

error                           = "fg_red_13_detailed_devil"
warning                         = "fg_yellow_12_rite_of_spring"
info                            = "fg_blue_08_widowmaker"
hint                            = "fg_cyan_03_shimmering_expanse"


[palette]
# === - Aumnechroma color palette - ===
#: Background
bg_01_darkcrust                 = "#040206"                                   
bg_02_remnant                   = "#05040d"                                   
bg_03_night                     = "#07030f"                                   
bg_04_monolith                  = "#0e0a18"                                   
bg_05_tristesse                 = "#120e20"                                   
bg_06_dusk                      = "#151028"                                   
bg_07_dark_knight               = "#18122b"                                   
bg_08_ghost                     = "#26144a"                                   
bg_09_champion_blue             = "#646886"                                   
                                                                              
#: Special
special_01_dahlia_purple        = "#7c6cac"                                   
special_02_coronation_blue      = "#5c4c9c"                                   
special_03_secretive            = "#493b89"                                   

#: Whites
fg_white_00_icy_landscape       = "#c8d0fc"                                   
fg_white_01_seashell            = "#fff4ef"                                   
fg_white_02_island_hopping      = "#f6e4d6"                                   
fg_white_03_warm_winter         = "#d6eee4"                                   
fg_white_04_azure               = "#ebfffc"                                   
fg_white_05_bubbles             = "#e1f9ff"                                   
fg_white_06_calm_iridescence    = "#faeedd"                                   
fg_white_07_hint_of_blue        = "#c0c4ff"                                   
fg_white_08_sugar_crystal       = "#f2eeff"                                   
fg_white_09_romantic_cruiser    = "#eadfef"                                   
fg_white_10_fairy_wings         = "#ffecf2"                                   
fg_white_11_icy_plains          = "#ced1fb"                                   
fg_white_12_cold_illusion       = "#b3b8ff"                                   

#: Cyans
fg_cyan_01_verdigris            = "#51eaf8"                                   
fg_cyan_02_windswept            = "#58cdff"                                   
fg_cyan_03_shimmering_expanse   = "#1dcde3"                                   
fg_cyan_04_thousand_sons        = "#03c2f4"                                   
fg_cyan_05_ocean_eyes           = "#a1eae4"                                   
fg_cyan_06_blue_bikini          = "#68b0e9"                                   
fg_cyan_07_libra_morpho         = "#c0e8ff"                                   
fg_cyan_08_ice_effect           = "#60d1ca"                                   
fg_cyan_09_lucea                = "#9fdae8"                                   
fg_cyan_10_lazy_day             = "#5cbcb6"                                   
fg_cyan_11_jade                 = "#92add1"                                   
fg_cyan_12_mint_macaron         = "#9dcff4"                                   
fg_cyan_13_shallow_water        = "#91f4fa"                                   
fg_cyan_14_aquella              = "#59b7d5"                                   

#: Blues
fg_blue_00_aero                 = "#9ab8f6"                                   
fg_blue_01_blue_genie           = "#a4abff"                                   
fg_blue_02_picnic_sky           = "#01c7ec"                                   
fg_blue_03_pool_tiles           = "#7ad0f0"                                   
fg_blue_04_moonstone            = "#7982ff"                                   
fg_blue_05_glitter_lake         = "#55abff"                                   
fg_blue_06_kindred              = "#60a8dd"                                   
fg_blue_07_rockman              = "#3aa6f4"                                   
fg_blue_08_widowmaker           = "#89a5ff"                                   
fg_blue_09_periwinkle           = "#8798fe"                                   
fg_blue_10_blue_sand            = "#b6b2f4"                                   
fg_blue_11_celeste              = "#b8e2fd"                                   
fg_blue_12_fennel_flower        = "#6e9cfe"                                   
fg_blue_13_pink_ocd             = "#633bfb"                                   
fg_blue_14_cobalite             = "#9994f9"                                   
fg_blue_15_blue_party           = "#675aff"                                   
fg_blue_16_dacnis               = "#52bee5"                                   
fg_blue_17_shneonblue           = "#5158ff"                                   
fg_blue_18_dried_lilac          = "#bbc0f2"                                   
fg_blue_19_carriage_ride        = "#9b9abf"                                   

#: Purples
fg_purple_01_myrtle_flower      = "#b4adfd"                                   
fg_purple_02_purple_sand        = "#c3aaf8"                                   
fg_purple_03_lavender_cream     = "#c4aff4"                                   
fg_purple_04_baby_purple        = "#c5bdfc"                                   
fg_purple_05_lavender_dreamer   = "#dcaafc"                                   
fg_purple_06_iridescent_purple  = "#9978d1"                                   
fg_purple_07_petal_plush        = "#dfa3f0"                                   
fg_purple_08_lovecloud          = "#edbeea"                                   
fg_purple_09_lavender_magenta   = "#c482e2"                                   
fg_purple_10_lilac_fluff        = "#c1a2ff"                                   
fg_purple_11_blossoms_in_spring = "#d690f5"                                   
fg_purple_12_dream_vapor        = "#bc96f9"                                   
fg_purple_13_bright_ube         = "#c5a4e9"                                   
fg_purple_14_lucius_lilac       = "#bfa0d0"                                   
fg_purple_15_lenurple           = "#b38ed6"                                   
fg_purple_16_violet_gems        = "#c2b1e6"                                   
fg_purple_17_venetian_night     = "#ab80fb"                                   
fg_purple_18_szollosi_grape     = "#7728ff"                                   
fg_purple_19_sweet_escape       = "#9562ff"                                   
fg_purple_20_irrigo             = "#935cfa"                                   
fg_purple_21_forgotten_purple   = "#ae87ff"                                   
fg_purple_22_lical_geode        = "#b18cfb"                                   
fg_purple_23_whisper_lilac      = "#bba8fc"                                   
fg_purple_24_aconite_violet     = "#9f4ded"                                   
fg_purple_25_lighter_purple     = "#bcaeff"                                   

#: Reds
fg_red_00_cardinal              = "#f4444f"                                   
fg_red_01_infrared              = "#ff4f5d"                                   
fg_red_02_festive_fennec        = "#ff5969"                                   
fg_red_03_nadeshiko             = "#f8aec4"                                   
fg_red_04_anime_blush           = "#fc74a8"                                   
fg_red_05_emberglow             = "#e4685d"                                   
fg_red_06_desire                = "#ff4d4d"                                   
fg_red_07_coralette             = "#fa5f69"                                   
fg_red_08_cyclamen              = "#f96996"                                   
fg_red_09_fuchsia_blush         = "#ffa799"                                   
fg_red_10_candy_bar             = "#ffb9d4"                                   
fg_red_11_cichlid               = "#f73159"                                   
fg_red_12_hell                  = "#f84752"                                   
fg_red_13_detailed_devil        = "#fc3559"                                   
fg_red_14_strawberry_field      = "#fb8681"                                   
fg_red_15_pure_hedonist         = "#ff426f"                                   

#: Orange
fg_orange_00_ryza_dust          = "#fa7333"                                   
fg_orange_01_heatstroke         = "#fa7c58"                                   
fg_orange_02_candyman           = "#ff9b75"                                   
fg_orange_03_rajah              = "#f8ba82"                                   
fg_orange_04_peach_cobbler      = "#ffb683"                                   
fg_orange_05_coral_sand         = "#e29e5d"                                   
fg_orange_06_caramel_ice        = "#eec8a7"                                   
fg_orange_07_optimist_gold      = "#ff8f4f"                                   
fg_orange_08_xanthous           = "#f6b642"                                   
fg_orange_09_celebration        = "#ffdba0"                                   
fg_orange_10_golden_apricot     = "#eab969"                                   
fg_orange_11_amber              = "#f8ab4b"                                   
fg_orange_12_chocobo_feather    = "#f29964"                                   
fg_orange_13_apocalyptic_orange = "#f49040"                                   
fg_orange_14_papaya_punch       = "#fc9f82"                                   
fg_orange_15_melon_red          = "#f2906a"                                   
fg_orange_16_kumquat            = "#fda86f"                                   
fg_orange_17_just_peachy        = "#f8b878"                                   
fg_orange_18_lightning_yellow   = "#faa334"                                   
fg_orange_19_whipped_apricot    = "#fcd3a6"                                   
fg_orange_20_peach_orange       = "#fccaa8"                                   

#: Yellow
fg_yellow_01_apricot_fool       = "#fdd2b8"                                   
fg_yellow_02_egg_yolk           = "#ffcd80"                                   
fg_yellow_03_solar_power        = "#f6bb43"                                   
fg_yellow_04_golden_gate        = "#d9c29c"                                   
fg_yellow_05_honey_crisp        = "#e9c058"                                   
fg_yellow_06_fashion_yellow     = "#ecbf36"                                   
fg_yellow_07_neon_light         = "#ffe55c"                                   
fg_yellow_08_silk_sails         = "#f6f2cf"                                   
fg_yellow_09_elfin              = "#e7f1a6"                                   
fg_yellow_10_viameter           = "#d5d841"                                   
fg_yellow_11_yippie_ya          = "#fbf8a0"                                   
fg_yellow_12_rite_of_spring     = "#ffeaa6"                                   
fg_yellow_13_unmellow           = "#fdfe6a"                                   

#: Green
fg_green_01_seductive_thorns    = "#a2c641"                                   
fg_green_02_acid_lime           = "#afdd35"                                   
fg_green_03_reef_refractions    = "#d8ec9a"                                   
fg_green_04_mulu_frog           = "#54c200"                                   
fg_green_05_taurus_forest_fern  = "#73bd48"                                   
fg_green_06_poisonous_dart      = "#7bde6d"                                   
fg_green_07_iguana_green        = "#75bb71"                                   
fg_green_08_goddess_of_dawn     = "#add7ae"                                   
fg_green_09_synthetic_mint      = "#9fffaf"                                   
fg_green_10_algal_fuel          = "#24c376"                                   

#: Misc
cursorline                      = "#0e0a18"
secondary_cursor                = "#b5a6a8"




